### ISSUE TITLE
Teamwork contract

### ISSUE THREAD

**Issue by RobBlumberg** [UBC-MDS/Kmeans_python#24]
We need to write up a teamwork contract to put in our private ubc.ca repos

**Comment by sreejithmunthikodu** [comment]
I think it is best to discuss this privately. But still a good idea to create an issue so that we can track the progress.

**Comment by sreejithmunthikodu** [comment]
As per our preliminary discussions, here is a draft copy of the teamwork contract. Please modify and add.

# Teamwork contract  
- We will try to finish work by Friday night so that Saturday can be used to deal with any unexpected bugs.
- Outside lab hours we are not scheduling any regular meetings. However, we will be meeting on a need basis 
    after giving at least 1-day notice to all teammates. 
- No meetings at a bar
- We will address TA’s comments as soon as possible. 
- We will communicate all issues to teammates as soon as possible.
- Saurav is responsible for the fit function.
- Rob is responsible for the summary and predicts functions. 
- James is responsible for the Silhouette function.
- Sree is responsible for the Elbow function
- We will decide on switching the roles between the R and Python projects in milestone 2.
- All members will take equal ownership of other tasks such as documentation, creating issues, closing issues. 
- In the event of major disagreements, try to resolve conflict within the team before escalating to the lab instructor for help in resolving the situation.
- Every member should inform his un-availability beforehand(at least 1 day), so others can share his part of the work if needed.

**Comment by RobBlumberg** [comment]
Think we should add a point about dealing with potential conflicts along the lines of:

- In the event of major disagreements, try to resolve conflict within the team before escalating to lab instructor for help on resolving situation.

**Comment by sreejithmunthikodu** [comment]
> * In the event of major disagreements, try to resolve conflict within the team before escalating to lab instructor for help on resolving situation.

Agree. Thanks, updated.

**Comment by saurav193** [comment]
Also please add, Every member should inform his un-availability beforehand(at least 1 day), so others can share his part of the work if needed.

**Comment by sreejithmunthikodu** [comment]
> Also please add, Every member should inform his un-availability beforehand(at least 1 day), so others can share his part of the work if needed.

Sounds good. Added. Thanks Saurav
